In [1]:
import numpy as np

In [2]:
num_lst = [1,2,3]

In [5]:
num_np = np.array(num_lst)

In [6]:
type(num_np)

numpy.ndarray

In [7]:
num_lst_3dim = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
num_np_3dim = np.array(num_lst_3dim)

In [12]:
num_np_3dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.linspace(0,10,3,endpoint=False)

array([0.        , 3.33333333, 6.66666667])

In [97]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
np.random.rand(10,2)

array([[0.85668977, 0.10115613],
       [0.80118393, 0.96924264],
       [0.73059726, 0.42514918],
       [0.65908129, 0.60661916],
       [0.44522452, 0.13713577],
       [0.46470498, 0.15160117],
       [0.06898175, 0.20601599],
       [0.64785515, 0.66237519],
       [0.28912409, 0.38685086],
       [0.63438364, 0.50202821]])

In [128]:
np.random.randint(2,10,3)

array([5, 2, 4], dtype=int32)

In [167]:
np.random.seed(42)
np.random.rand(2)

array([0.37454012, 0.95071431])

In [168]:
arr = np.arange(0,25)

In [177]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [178]:
randarr = np.random.randint(0,101,10)

In [180]:
randarr.max()

np.int32(99)

In [181]:
randarr.min()

np.int32(20)

In [187]:
randarr.argmin()

np.int64(2)

In [184]:
arr.shape

(25,)

In [185]:
arr = arr.reshape(5,5)

In [216]:
li = list(range(11))

In [217]:
arr.shape

(5, 5)

In [239]:
ar = np.arange(0,11)

In [225]:
ar[1:7:2],li[1:7:2]

(array([1, 3, 5]), [1, 3, 5])

In [221]:
ar[:-2],li[:-2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), [0, 1, 2, 3, 4, 5, 6, 7, 8])

In [224]:
ar[-1::-1],li[-1::-1]

(array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]),
 [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [242]:
ar[:3] = 10

In [243]:
ar

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9, 10])

In [244]:
li[:3] = [10,10,10]

In [246]:
lst = li[:3]
lst = [11,11,11]

In [248]:
li

[10, 10, 10, 3, 4, 5, 6, 7, 8, 9, 10]

In [252]:
ar = np.arange(1,51).reshape(5,10)

In [253]:
ar

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [263]:
ar[:3,2:]

array([[ 3,  4,  5,  6,  7,  8,  9, 10],
       [13, 14, 15, 16, 17, 18, 19, 20],
       [23, 24, 25, 26, 27, 28, 29, 30]])

In [267]:
ar[ar>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [271]:
np.max(ar)

np.int64(50)

In [272]:
ar.max()

np.int64(50)