In [1]:
import torch

In [2]:
import numpy as np

In [4]:
torch.__version__

'2.10.0+cpu'

In [6]:
arr = np.array([1,10,12,3])

In [7]:
arr.dtype

dtype('int64')

In [8]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr)

In [10]:
type(x)

torch.Tensor

In [11]:
x

tensor([ 1, 10, 12,  3])

In [12]:
torch.as_tensor(arr)

tensor([ 1, 10, 12,  3])

In [13]:
x.dtype

torch.int64

In [14]:
arr2d = np.arange(0.0,12.0)

In [15]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [16]:
arr2d = arr2d.reshape(4,3)

In [17]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [18]:
x2 = torch.from_numpy(arr2d)

In [19]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [20]:
arr[0] = 100

In [21]:
arr

array([100,  10,  12,   3])

In [22]:
x

tensor([100,  10,  12,   3])

In [23]:
my_tensor = torch.tensor(arr)

In [24]:
my_other_tensor = torch.from_numpy(arr)

In [25]:
arr[0] = 999

In [26]:
my_tensor,my_other_tensor

(tensor([100,  10,  12,   3]), tensor([999,  10,  12,   3]))

In [28]:
ten = torch.Tensor(arr)

In [30]:
ten.dtype

torch.float32

In [31]:
arr[0] = 123

In [32]:
ten

tensor([999.,  10.,  12.,   3.])

In [34]:
torch.FloatTensor(arr)

tensor([123.,  10.,  12.,   3.])

In [54]:
torch.empty(2,2)

tensor([[12.,  3.],
        [ 0.,  0.]])

In [74]:
torch.zeros(2,2,dtype=torch.int64)

tensor([[0, 0],
        [0, 0]])

In [75]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [78]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [79]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [80]:
my_tensor = torch.tensor([1,2,3])

In [82]:
my_tensor = torch.tensor([1,2,3])

In [83]:
my_tensor = my_tensor.type(torch.int32)

In [84]:
my_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [85]:
torch.rand(4,3)

tensor([[0.6229, 0.4941, 0.2920],
        [0.9233, 0.3212, 0.3276],
        [0.2773, 0.8235, 0.4832],
        [0.2594, 0.6747, 0.8310]])

In [86]:
torch.randn(4,3)

tensor([[-1.0978, -0.7443,  1.1573],
        [ 1.4120, -1.8317,  0.6805],
        [-0.4697,  0.5860, -1.9733],
        [-0.1463,  0.3603,  0.3813]])

In [90]:
torch.randint(low=1,high=3,size=(5,5))

tensor([[2, 1, 2, 2, 2],
        [1, 2, 2, 1, 1],
        [2, 1, 2, 1, 1],
        [2, 1, 1, 1, 1],
        [2, 2, 1, 2, 1]])

In [91]:
x = torch.zeros(2,5)

In [93]:
x.shape

torch.Size([2, 5])

In [110]:
torch.manual_seed(42)
torch.rand_like(x)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332]])

In [111]:
x = torch.arange(6).reshape(3,2)

In [114]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [115]:
x[1,1]

tensor(3)

In [116]:
x[:,1]

tensor([1, 3, 5])

In [118]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [119]:
x = torch.arange(10)

In [120]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
l = x.view(2,5)

In [127]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [128]:
indexing is same in both numpy arrays and tensors.
x.view(2,5) # We can view it in the specified shape
a + b, a - b etc..
x.add(x2)
x.mul(x2)

SyntaxError: invalid syntax (875519909.py, line 1)

In [ ]:
x