In [1]:
import torch

In [32]:
x = torch.tensor(2.0,requires_grad=True)

In [33]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [34]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [35]:
type(y)

torch.Tensor

In [36]:
y.backward()

In [37]:
x.grad

tensor(93.)

In [15]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)

In [17]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [18]:
y = 3*x + 2

In [19]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [20]:
z = 2*y**2

In [21]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [22]:
out = z.mean()

In [23]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [24]:
out.backward()

In [25]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])


In [26]:
out

tensor(140., grad_fn=<MeanBackward0>)